App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^marketwithparams/(?P<typeid>\d+)/(?P<childcid>\d+)/(?P<order_rule>\d+)/', views.market_with_params,
        name='market_with_params'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^checkuser/', views.check_user, name='check_user'),
    url(r'logout/', views.logout, name='logout'),
    url(r'sendemail/',views.send_email),
]

GPAXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from GPAXF import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('App.urls', namespace='axf')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

templates/main/cart.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/cart.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/main/js/cart.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="cart">
        <h3>Cart</h3>
        <div class="full">
            <section>
                <ul>
                    <li>收&nbsp;&nbsp;货&nbsp;&nbsp;人:&nbsp;Rock</li>
                    <li>电&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;话:&nbsp;110</li>
                    <li>地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址:&nbsp;宝盛里</li>
                </ul>

                <div class="bill">

                    <p>闪送超市</p>
                    <p>0元起送满30免运费22:00前可送达</p>
                    <a href="#">凑单专区</a>

                </div>

                <div class="delivery">
                    <span>收货时间</span>
                    <span>一小时内送达</span>
                    <a href="#">可预订&gt;</a>
                </div>

                <div class="delivery">
                    <span>收获备注</span>
                    <input type="text" placeholder="可输入100字以内的特殊要求">
                </div>

                <ul>
                    {% for cart in carts %}
                        <li class="menuList" cartid="{{ cart.id }}">
                            <div class="confirm">
                                <span>
                                    {% if cart.c_is_select %}
                                        <span>√</span>
                                        {% else %}
                                        <span></span>
                                    {% endif %}
                                </span>
                            </div>
                            <a href="#">
                                <img src="{{ cart.c_goods.productimg }}" alt="{{ cart.c_goods.productlongname }}">
                                <p>{{ cart.c_goods.productlongname }}</p>
                                <p class="presentPrice">{{ cart.c_goods.price }}</p>
                            </a>


                            <section>
                                <button class="subShopping">-</button>
                                <span>{{ cart.c_goods_num }}</span>
                                <button class="addShopping">+</button>
                            </section>

                        </li>
                    {% endfor %}

                </ul>

                <div class="payTheBill">
                    <div class="all_select">
                        <span>
                            {% if is_all_select %}
                                <span>√</span>
                                {% else %}
                                <span></span>
                            {% endif %}
                        </span>
                    </div>

                    <p>
                        <span>全选</span>
                        <span>共计:</span>
                        <span id="total_price">{{ total_price }}</span>
                    </p>

                    <span id="make_order">下单</span>
                </div>

            </section>


        </div>
    </div>

{% endblock %}

templates/main/home.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/home.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'axf/main/js/home.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="home">
{#        首页顶部轮播       #}
        <div class="swiper-container" id="topSwiper">
            <div class="swiper-wrapper">
                {% for main_wheel in main_wheels %}

                    <div class="swiper-slide">
                        <img src="{{ main_wheel.img }}" alt="{{ main_wheel.name }}">
                    </div>
                {% endfor %}
            </div>
            <div class="swiper-pagination"></div>
        </div>

{#       首页顶部的导航      #}
        <div class="topMenu">
            <nav>
                <ul>
                    {% for main_nav in main_navs %}
                        <li>
                            <img src="{{ main_nav.img }}" alt="{{ main_nav.name }}">
                            <span>{{ main_nav.name }}</span>
                        </li>
                    {% endfor %}

                </ul>
            </nav>
        </div>

{#        首页必购      #}
        <div class="swiper-container" id="swiperMenu">
            <ul class="swiper-wrapper">
                {% for main_mustbuy in main_mustbuys %}

                    <li class="swiper-slide">
                        <img src="{{ main_mustbuy.img }}" alt="{{ main_mustbuy.name }}">
                    </li>
                {% endfor %}
            </ul>
        </div>

{#       首页商店       #}
        <div class="shop_container">
            <h2>
                <img src="{{ main_shop0_1.0.img }}" alt="{{ main_shop0_1.0.name }}">
            </h2>

            <fieldset>
                {% for mains_shop in main_shop1_3 %}
                    <a href="#">
                        <img src="{{ mains_shop.img }}" alt="{{ mains_shop.name }}">
                    </a>
                {% endfor %}

            </fieldset>

            <ul>
                {% for main_shop in main_shop3_7 %}
                    <li>
                        <img src="{{ main_shop.img }}" alt="{{ main_shop.name }}">
                        <span>{{ main_shop.name }}</span>
                    </li>
                {% endfor %}

            </ul>

            <ol>
                {% for main_shop in main_shop7_11 %}
                    <li>
                        <a href="#">
                            <img src="{{ main_shop.img }}" alt="{{ main_shop.name }}">
                        </a>
                    </li>
                {% endfor %}

            </ol>

        </div>

{#        首页主显示    #}
        <ul>
            {% for main_show in main_shows %}
                <li class="mainInfo">
                    <section>
                        <h3>{{ main_show.name }}
                            <a href="#">更多&gt;</a>
                            <span></span>
                        </h3>

                        <div>
                            <a href="#">
                                <img src="{{ main_show.img }}" alt="{{ main_show.name }}">
                            </a>
                        </div>

                        <ul>
                            <li>
                                <a href="#">
                                    <img src="{{ main_show.img1 }}" alt="{{ main_show.longname1 }}">
                                    <p class="description">{{ main_show.longname1 }}</p>
                                    <span>{{ main_show.price1 }}</span>
                                    <s>{{ main_show.marketprice1 }}</s>
                                </a>
                                <button>
                                    <span>+</span>
                                </button>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="{{ main_show.img2 }}" alt="{{ main_show.longname2 }}">
                                    <p class="description">{{ main_show.longname2 }}</p>
                                    <span>{{ main_show.price2 }}</span>
                                    <s>{{ main_show.marketprice2 }}</s>
                                </a>
                                <button>
                                    <span>+</span>
                                </button>
                            </li>
                            <li>
                                <a href="#">
                                    <img src="{{ main_show.img3 }}" alt="{{ main_show.longname3 }}">
                                    <p class="description">{{ main_show.longname3 }}</p>
                                    <span>{{ main_show.price3 }}</span>
                                    <s>{{ main_show.marketprice3 }}</s>
                                </a>
                                <button>
                                    <span>+</span>
                                </button>
                            </li>
                        </ul>

                    </section>
                </li>
            {% endfor %}

        </ul>

    </div>
{% endblock %}

templates/main/market.html
{% extends 'base_main.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/market.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/main/js/market.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="market">
        {#        左边的大类型导航     #}
        <aside>
            <ul>
                {% for foodtype in foodtypes %}
                    <li>
                        <a href="{% url 'axf:market_with_params' typeid=foodtype.typeid childcid=0 order_rule=0 %}">{{ foodtype.typename }}</a>
                        {% ifequal foodtype.typeid typeid %}
                            <span class="yellowSlide"></span>
                        {% endifequal %}

                    </li>
                {% endfor %}

            </ul>
        </aside>


        <section>
            <nav>
                <ul>
                    <li id="all_types"><span>全部分类 <span class="glyphicon glyphicon-chevron-down"></span></span></li>
                    <li id="sort_rule"><span>综合排序 <span class="glyphicon glyphicon-chevron-down"></span></span></li>
                </ul>
            </nav>

            <menu>
                <ul>
                    {% for goods in goods_list %}
                        <li>
                            <a href="#">
                                <img src="{{ goods.productimg }}" alt="{{ goods.productlongname }}">
                                <div class="shoppingInfo">
                                    <h6>{{ goods.productlongname }}</h6>
                                    <p class="detailTag">
                                        <span>精选</span>
                                        <span></span>
                                    </p>
                                    <p class="unit">{{ goods.specifics }}</p>
                                    <p class="price">
                                        <span>{{ goods.price }}</span>
                                        <s>{{ goods.marketprice }}</s>
                                    </p>
                                </div>
                            </a>

                            <section>
                                <button class="subShopping">－</button>
                                <span>0</span>
                                <button goodsid="{{ goods.id }}" class="addShopping">＋</button>
                            </section>
                        </li>
                    {% endfor %}

                </ul>
                <div id="all_types_container">
                    <div>
                        {% for foodtype_childname in foodtype_childname_list %}

                            {% ifequal foodtype_childname.1 childcid %}
                                <a href="{% url 'axf:market_with_params' typeid=typeid childcid=foodtype_childname.1 order_rule=0 %}">
                                    <button class="btn btn-success">{{ foodtype_childname.0 }}</button>
                                </a>
                            {% else %}
                                <a href="{% url 'axf:market_with_params' typeid=typeid childcid=foodtype_childname.1 order_rule=0 %}">
                                    <button class="btn btn-default">{{ foodtype_childname.0 }}</button>
                                </a>
                            {% endifequal %}


                        {% endfor %}
                    </div>
                </div>

                <div id="sort_rule_container">
                    <div>

                        {% for order_rule in order_rule_list %}

                            {% ifequal order_rule_view order_rule.1 %}
                                <a href="{% url 'axf:market_with_params' typeid=typeid childcid=childcid order_rule=order_rule.1 %}">
                                    <button class="btn btn-success">{{ order_rule.0 }}</button>
                                </a>
                            {% else %}
                                <a href="{% url 'axf:market_with_params' typeid=typeid childcid=childcid order_rule=order_rule.1 %}">
                                    <button class="btn btn-default">{{ order_rule.0 }}</button>
                                </a>
                            {% endifequal %}

                        {% endfor %}


                    </div>
                </div>
            </menu>

        </section>


    </div>
{% endblock %}

templates/main/mine.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/mine.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/main/js/mine.js' %}"></script>
{% endblock %}


{% block content %}
    <div id="mine">
        <div class="fixed">
            <span>
                {% if is_login %}
                    <img class="u_icon" src="{{ icon }}" alt="{{ username }}">
                {% else %}
                    <span class="glyphicon glyphicon-user"></span>
                {% endif %}
            </span>
            {% if is_login %}
                <p>{{ username }}</p>
            {% else %}
                <p id="not_login">未登录</p>
            {% endif %}

            <p>
                <span class="glyphicon glyphicon-fire"></span>
                <span>等级</span>
            </p>

            {% if not is_login %}
                <div id="regis">注册</div>
            {% endif %}

            <p>
                <span class="glyphicon glyphicon-heart"></span>
                <span>商品收藏</span>
            </p>

        </div>

        <div class="mine">
            <p>
                <span>全部订单</span>
                <a href="#">全部订单></a>
            </p>

            <nav id="nav">
                <ul>
                    <li id="not_pay">
                        {% ifnotequal order_not_pay 0 %}
                            <span class="badge">
                                {{ order_not_pay }}
                        </span>
                        {% endifnotequal %}
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            <dd>待付款</dd>
                        </dl>
                    </li>
                    <li>
                        {% ifnotequal order_not_receive 0 %}
                            <span class="badge">
                                {{ order_not_receive }}
                         </span>
                        {% endifnotequal %}
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            </dt>
                            <dd>待收货</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-pencil"></span>
                            </dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-retweet"></span>
                            </dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-bullhorn"></span>
                            </dt>
                            <dd>积分商城</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-credit-card"></span>
                            </dt>
                            <dd>优惠卷</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-import"></span>
                            </dt>
                            <dd>收货地址</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-phone-alt"></span>
                            </dt>
                            <dd>客服反馈</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-asterisk"></span>
                            </dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>

            {% if is_login %}
                <p>
                    <a href="{% url 'axf:logout' %}">退出</a>
                </p>
            {% endif %}

        </div>

    </div>
{% endblock %}