App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^marketwithparams/(?P<typeid>\d+)/(?P<childcid>\d+)/(?P<order_rule>\d+)/', views.market_with_params,
        name='market_with_params'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^checkuser/', views.check_user, name='check_user'),
    url(r'logout/', views.logout, name='logout'),
    url(r'sendemail/',views.send_email),
]

GPAXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from GPAXF import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('App.urls', namespace='axf')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

templates/user/activate.html
<h4>Dear {{ username }}:</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;欢迎注册爱鲜蜂VIP，但您的账号没有进行激活认证，请点击下面的激活按钮进行激活</p>
<a href="{{ activate_url }}">激活</a>
<p>如上面的激活按钮不可用，请将下面的地址复制到浏览器进行激活</p>
<p>{{ activate_url }}</p>
<h6>&nbsp;&nbsp;&nbsp;&nbsp;Best Wishes</h6>
<p>From AXF Team</p>

templates/user/activate_fail.html
{% extends 'base_user.html' %}

{% block content %}
    <div>

        <h3>激活失败，请重新申请激活</h3>

    </div>
{% endblock %}

templates/user/login.html
{% extends 'base_user.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}

{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/login.js' %}"></script>
{% endblock %}



{% block content %}
    <div class="container">
        <form method="post" action="{% url 'axf:login' %}" onsubmit="return parse_data()">

            {% csrf_token %}

            <p>{{ error_message }}</p>

            <div class="form-group">
                <label for="username_input">用户名</label>
                <input name="username" type="text" class="form-control" id="username_input" placeholder="用户名/邮箱">
            </div>

            <div class="form-group">
                <label for="password_input">密码</label>
                <input name="password" type="password" class="form-control" id="password_input" placeholder="请输入密码">
            </div>


            <button type="submit" class="btn btn-success btn-block">登录</button>
        </form>
    </div>
{% endblock %}

templates/user/register.html
{% extends 'base_user.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/user/css/register.css' %}">
{% endblock %}


{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/register.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" enctype="multipart/form-data" action="{% url 'axf:register' %}" onsubmit="return check()">

            {% csrf_token %}

            <div class="form-group">
                <label for="username_input">用户名</label>
                <input name="username" type="text" class="form-control" id="username_input" placeholder="请输入用户名">
                <span id="username_info"></span>
            </div>
            <div class="form-group">
                <label for="email_input">邮箱</label>
                <input name="email" type="text" class="form-control" id="email_input" placeholder="请输入邮箱">
            </div>
            <div class="form-group">
                <label for="password_input">密码</label>
                <input name="password" type="password" class="form-control" id="password_input" placeholder="请输入密码">
            </div>
            <div class="form-group">
                <label for="password_confirm_input">确认密码</label>
                <input type="password" class="form-control" id="password_confirm_input" placeholder="请再次输入密码">
            </div>
            <div class="form-group">
                <label for="icon_input">头像</label>
                <input name="icon" type="file" id="icon_input">
            </div>

            <button type="submit" class="btn btn-success btn-block">注册</button>
        </form>
    </div>
{% endblock %}